#!/usr/bin/with-contenv bash

# variables
HOME=/config
WORK_TREE=--work-tree="$HOME"
GIT_DIR=--git-dir="$HOME/.dotfiles"

# create folders
mkdir -p "$HOME"/workspace

# personal setup
if [ -d "$HOME/.dotfiles" ]
then
  echo "**** updating personal setup ****"
  git $GIT_DIR $WORK_TREE pull
else
  echo "**** setting personal setup ****"
  git clone $GIT_REPOSITORY /tmp/dotfiles
  cp -aR /tmp/dotfiles/. $HOME
  rm -rf /tmp/*
  mv $HOME/.git $HOME/.dotfiles
  echo ".dotfiles" >> $HOME/.gitignore
  git $GIT_DIR $WORK_TREE config --local status.showUntrackedFiles no
fi

# change shell
usermod -s /usr/bin/fish ${USER_NAME}
