#!/usr/bin/with-contenv bash

# variables
HOME=/config
WORK_TREE=--work-tree="$HOME"
GIT_DIR=--git-dir="$HOME/.dotfiles"

# make directories
mkdir -p "$HOME"/workspace

# git config
if [ ! -z "$GIT_USER_NAME" ] && [ ! -z "$GIT_USER_EMAIL" ]; then
  git config --global user.name "$GIT_USER_NAME"
  git config --global user.email "$GIT_USER_EMAIL"
  git config --global core.editor nvim
fi

# oh-my-zsh
if [ -z "$ZSH" ] && [ ! -d "$HOME/.oh-my-zsh" ]; then
  echo "**** installing oh my zsh ****"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

# get dotfiles
if [ -d "$HOME/.dotfiles" ]
then
  echo "**** updating personal setup ****"
  git $GIT_DIR $WORK_TREE pull
else
  echo "**** setting personal setup ****"
  git clone $GIT_REPOSITORY /tmp/dotfiles
  cp -aR /tmp/dotfiles/. $HOME
  rm -rf /tmp/*
  mv $HOME/.git $HOME/.dotfiles
  echo ".dotfiles" >> $HOME/.gitignore
  git $GIT_DIR $WORK_TREE config --local status.showUntrackedFiles no
fi

# change shell
usermod -s /bin/zsh ${USER_NAME}

# permissions
chown -R "$USER_NAME":"$USER_NAME" "$HOME"